language: c

notifications:
  email: false

git:
  depth: 3

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5']
      env: COMP=gcc-5

    - os: osx
      osx_image: xcode
      env: COMP=clang

script: 
    - cd bin
    - CC=$COMP cmake ..
    - make VERBOSE=1

