language: python
dist: xenial
group: travis_latest

git:
  depth: 25
  quiet: true

os:
- linux

python:
- 3.6

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy .
    after_success:
    - pytest --cov
    - coveralls

install:
- pip install -e .[tests]

- cd build
- cmake ..
- cmake --build .

script:
- ctest --output-on-failure
- cd $TRAVIS_BUILD_DIR

- pytest -rsv
