language: c

notifications:
  email: false

git:
  depth: 1

matrix:
  include:
    - os: linux
      sudo: true
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5']
      env: COMP=gcc-5

    - os: osx
      osx_image: xcode7.3 # or whatever the latest is
      compiler: clang
      env: COMP=clang

script: 
    - cd bin
    - CC=$COMP cmake ..
    - make VERBOSE=1

