name: ci

on:
  push:
    paths:
      - "**.py"
      - "**.c"
      - "**.cpp"
      - "**.cmake"
      - "**/CMakeLists.txt"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CTEST_NO_TESTS_ACTION: error
  CMAKE_BUILD_TYPE: Release


jobs:

  linux:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - run: cmake -B build
    - run: cmake --build build

    - run: ctest --test-dir build -V

    - run: pip install -e .[lint,tests]
    - run: flake8
    - run: mypy .
    - run: pytest
