name: ci

on:
  push:
    paths:
      - "**.py"
      - "**.c"
      - "**.cmake"
      - "**/meson.build"
      - "**/CMakeLists.txt"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: cmake -B build
    - run: cmake --build build

    - run: ctest -V
      working-directory: build

    - run: pip install -e .[lint,tests]
    - run: flake8
    - run: mypy .
    - run: pytest

  macos:
    if: false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: cmake -B build
    - run: cmake --build build --parallel
    - run: ctest -V
      working-directory: build

    - run: pip install -e .[tests]
    - run: pytest
