name: ci

env:
  CI: true

on: [push, pull_request]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install cmake
    - run: |
        cmake -B build
        cmake --build build

    - run: ctest -V
      working-directory: build
    - run: pip install -e .[lint,tests]
    - run: |
        flake8
        mypy .
    - run: pytest
      working-directory: build

  macos:
    if: false
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: cmake -B build
    - run: cmake --build build --parallel
    - run: ctest -V
      working-directory: build
    - name: Install dependencies
      run: pip install -e .[tests]
    - run: pytest
